@startgantt
Project starts the 15th of dec 2018

[Analysis] as [A] lasts 30 days

[Abgabe Projektplanung] happens at 2019-01-11

[Design] as [D] lasts 15 days
[Abgabe Arch & Komp] happens at 2019-01-19
[D] starts at [A]'s end

[Implementation] as [I] lasts 30 days
[Abgabe Zwischenstand] happens at 2019-02-15
[I] starts at [D]'s end

[Testing] as [T] lasts 10 days
[T] starts at [I]'s end
[Abgabe Doku] happens at 2019-03-09
[Abgabe App] happens at 2019-03-09

[Deployment] as [DD] lasts 6 days
[DD] starts at [T]'s end
[Präsentation] happens at 2019-03-16

@endgantt